let Count = 0
let o = Math.floor(Math.random() * 10);
let j = Math.floor(Math.random() * 10);
let Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
 o = Math.floor(Math.random() * 10);
 j = Math.floor(Math.random() * 10);
 Otvet = prompt(`${o}+${j}`, '');

if (Otvet == (o + j)) {
  Count++;
  alert('Верно!');
} else {
  alert('Неправильно.');
}
alert(`Верно ${Count} из 10`)